### ISSUE TITLE
运行 simplepacker 提示 可执行文件格式错误

### ISSUE THREAD

**Issue by colin4124** [skykapok/dawn#1]
运行环境是 archlinux，执行 ./export.sh 的时候提示：

bash: ./simplepacker: cannot execute binary file: 可执行文件格式错误

**Comment by skykapok** [comment]
仓库里的simplepacker是在mac下编译的，你可以自己编译一个simplepacker替换上去就行了。
simplepacker现在也没有linux下的makefile，可以拿mac的来改改。
